services:
  express-app:
    image: 050629/express-app:latest
    ports:
      - 8080:8080
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --poll-interval 60
    restart: unless-stopped
